"""
Demo: How an AI agent would use the auto-generated GitHub tool
"""
import sys
import os
sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'generated_tools'))

# Import the auto-generated tool
exec(open('generated_tools/api.github.com.py').read())
github = ApiGithubCom()

# Agent initializes the tool
github = ApiGithubCom()

# Agent makes actual API calls
print("Testing GitHub API tool generated by Agent Nexus...\n")

# Test 1: Get GitHub API root
response = github._headers()
print(f"1. Headers configured: {response}")

# Test 2: Make a real API call to GitHub
import requests
response = requests.get(f"{github.base_url}/users/octocat", headers=github._headers())
print(f"\n2. Fetched GitHub user 'octocat':")
print(f"   Status: {response.status_code}")
if response.status_code == 200:
    data = response.json()
    print(f"   Name: {data.get('name')}")
    print(f"   Bio: {data.get('bio')}")
    print(f"   Public Repos: {data.get('public_repos')}")
    print(f"   Followers: {data.get('followers')}")

# Test 3: Search repositories
response = requests.get(f"{github.base_url}/search/repositories?q=elasticsearch", headers=github._headers())
print(f"\n3. Searched for 'elasticsearch' repos:")
print(f"   Status: {response.status_code}")
if response.status_code == 200:
    data = response.json()
    print(f"   Total found: {data.get('total_count')}")
    if data.get('items'):
        print(f"   Top result: {data['items'][0]['full_name']}")

print("\n✓ Agent successfully used auto-generated GitHub tool!")
